### ISSUE TITLE
Escaping keyword-like column names in prepared query

### ISSUE THREAD

**Issue by rijad-cz** [pomm-project/Foundation#20] opened 2015-02-24 13:57 UTC
Hello, I have a following problem with pomm. When I use collumn with name for example "limit" so I end with an error. 

The problem i following; Pomm generates prepared query for example: 

```sql
PREPARE ===
insert into travel_maxima_v1.tariffs ("product", "risk", "limit", "zone", "tariff") values ($1::travel_maxima_v1.product,$2::travel_maxima_v1.risk,$3::travel_maxima_v1.limit,$4::travel_maxima_v1.zone,$5::int4) returning id as id, uid as uid, created_at as created_at, created_by as created_by, updated_at as updated_at, updated_by as updated_by, product as product, risk as risk, limit as limit, zone as zone, tariff as tariff
 ===%
```

The whole INSERT is properly escaped, bud in the "returning" part is limit as limit. It ends with an error.
Could you fix it? 

Thank you.

**Comment by chanmix51** [comment] 2015-02-24 14:05
Yes, can you please provide type definition for `product` or `risk` so we could write a test case for this issue ?

**Comment by rijad-cz** [comment] 2015-02-24 18:11
Of course, here are my types and table definitions 

```sql
CREATE TYPE travel_maxima_v1."limit" AS ENUM
   ('A',
    'B',
    'C');
```

```sql
CREATE TYPE travel_maxima_v1.product AS ENUM
   ('MAXCESTA');
```

```sql
CREATE TYPE travel_maxima_v1.risk AS ENUM
   ('MEDICAL_EXPENSES',
    'LIABILITY',
    'BAGGAGE');
```

```sql
CREATE TYPE travel_maxima_v1.zone AS ENUM
   ('EUROPE');
```

```sql
CREATE TABLE travel_maxima_v1.tariffs
(
  id serial NOT NULL,
  uid uuid DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by integer NOT NULL DEFAULT 1,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by integer NOT NULL DEFAULT 1,
  product travel_maxima_v1.product NOT NULL,
  risk travel_maxima_v1.risk NOT NULL,
  "limit" travel_maxima_v1."limit" NOT NULL,
  zone travel_maxima_v1.zone NOT NULL,
  tariff integer NOT NULL,
  CONSTRAINT tariffs_pkey PRIMARY KEY (id)
)
```

All types are enums.

Thanks

**Comment by rijad-cz** [comment] 2015-02-24 18:23
When you try, that what I wrote, you will get an another error, that I reported in another issue https://github.com/pomm-project/Foundation/issues/21

**Comment by chanmix51** [comment] 2015-02-25 10:23
Does this problem still occure ?

**Comment by rijad-cz** [comment] 2015-02-25 10:31
Yes a have the most recent commit 4255809d0ab5e4732d24e322e080c61e9d3fd369 and this problem still occurs

**Comment by chanmix51** [comment] 2015-02-25 10:37
Can you provide the error message ?

**Comment by rijad-cz** [comment] 2015-02-25 10:42
PHP Fatal error:  Uncaught exception 'PommProject\Foundation\Exception\SqlException' with message '
SQL error state '42601' [ERROR]
====
ERROR:  syntax error at or near "limit"
LINE 1: ... as updated_by, product as product, risk as risk, limit as l...
                                                             ^

====
«PREPARE ===
insert into travel_maxima_v1.tariffs ("product", "risk", "limit", "zone", "tariff") values ($1::travel_maxima_v1.product,$2::travel_maxima_v1.risk,$3::travel_maxima_v1.limit,$4::travel_maxima_v1.zone,$5::int4) returning id as id, uid as uid, created_at as created_at, created_by as created_by, updated_at as updated_at, updated_by as updated_by, product as product, risk as risk, limit as limit, zone as zone, tariff as tariff
 ===».' in /Users/rijad/Sites/api.finance.cz/extensions/pomm-project/foundation/sources/lib/Session/Connection.php:307
Stack trace:
#0 /Users/rijad/Sites/api.finance.cz/extensions/pomm-project/foundation/sources/lib/Session/Connection.php(436): PommProject\Foundation\Session\Con in /Users/rijad/Sites/api.finance.cz/extensions/pomm-project/foundation/sources/lib/Session/Connection.php on line 307

Fatal error: Uncaught exception 'PommProject\Foundation\Exception\SqlException' with message ' in /Users/rijad/Sites/api.finance.cz/extensions/pomm-project/foundation/sources/lib/Session/Connection.php on line 307

**Comment by chanmix51** [comment] 2015-02-25 11:27
Ok. `LIMIT` is a SQL reserved word. As it is not quoted by the query it is interpreted by the database parser. Types must be double quoted in `WriteQueries`.

**Comment by chanmix51** [comment] 2015-02-25 11:43
The problem is handled in the Foundation package. Now, the CLI must generate types with proper schema and quoted types.

**Comment by rijad-cz** [comment] 2015-02-25 12:53
I have the most recent commit 01560e83630172fa4e1f8a5f85a29fb1b6640429 I have generated new models and it still not works. 

The problem is the same. When I use "insertOne" method, pomm generates prepared query like this

```sql
«PREPARE ===
insert into travel_maxima_v1.tariffs ("product", "risk", "limit", "zone", "tariff") values ($1::travel_maxima_v1.product,$2::travel_maxima_v1.risk,$3::travel_maxima_v1.limit,$4::travel_maxima_v1.zone,$5::int4) 
returning id as id, uid as uid, created_at as created_at, created_by as created_by, updated_at as updated_at, updated_by as updated_by, product as product, risk as risk, limit as limit, zone as zone, tariff as tariff
 ===»
``` 

the whole part insert into table ("column", ....) values ($x::type) is escaped properly. but the returning clause isn't properly escaped. Here occur 'limit as limit' and it causes the SQL error. 

 returning clause generated by pomm:

```sql
returning id as id, uid as uid, created_at as created_at, created_by as created_by, updated_at as updated_at, updated_by as updated_by, product as product, risk as risk, limit as limit, zone as zone, tariff as tariff
```

It should be 

```sql
returning id as id, uid as uid, created_at as created_at, created_by as created_by, updated_at as updated_at, updated_by as updated_by, product as product, risk as risk, "limit" as "limit", zone as zone, tariff as tariff
```

If I use a column named for example order, it will end with the same error because, all columns named same as the reserver keywords have to escaped in the returning clause too. 

Could you check it again please? 

Thank you

**Comment by chanmix51** [comment] 2015-02-25 13:48
I did dive into the code to see how this could be made. The problem here comes from how the PHP's Postgresql API does works. It does not distinguish identifiers that needs to be escaped from others and does escape everything. 

So far a projection formatting could be

```
… returning "id" as "id", "uid" as "uid", …
```

But it should also be able to format with table alias:

```
… returning "my_table"."id" as "id", "my_table"."uid" as "uid",…
```

This is not really a problem so far, problems come when projection is augmented with user defined fields like:

```php
$projection->setField('age', 'age(%birthdate)', 'int4');
```
The projection should output something like:

```
… returning my_table."id" as "id", …, age(my_table."birthdate") as "age"
```
Pomm does not know how to detect the field to properly quote it from that input. This means the programer could escape it himself:

```php
$projection->setField('age', 'age(%"birthdate")', 'int4');
```

But in this case, how to tell Pomm not to quote this field when formatting the projection and in the same time to quote other "simple" fields (like "id") ?

I do agree there must be a solution as fields in the formatted projection must be properly quoted. There are no quick fix for this. If you are in a hurry and have a hand on your schema definition I would suggest you change your fields and types names for now. (I am sorry about this).

One solution would be to specify field names as tokens like `%field name%` This way even field names with whitespaces could be found and properly escaped.

```php
$projection->setField('age', 'age(%his birthdate%)', 'int4');
// returning "id" as "id", …, age("his birthdate") as "age", …
```

This breaks existing applications so a communication prior to the change should be made.

**Comment by chanmix51** [comment] 2015-02-25 14:16
The `%field name%` syntax may collide with the use of the [modulo operator](http://www.postgresql.org/docs/9.2/static/functions-math.html). An alternate syntaxe would be `%:my field:%`

Since [SQL identifiers](http://www.postgresql.org/docs/9.1/static/sql-syntax-lexical.htm) must begin with a letter or an underscore this notation prevent any collision risk. 

Comments ?

**Comment by Pierozi** [comment] 2015-02-25 14:22
:+1: easy to read and safety.

**Comment by rijad-cz** [comment] 2015-02-25 17:22
I think, that the syntax like %:my field:% is good choice.

**Comment by chanmix51** [comment] 2015-02-25 20:24
I have pushed this change in a branch `projection` for now for tests and adjustments.

**Comment by tlode** [comment] 2015-02-25 21:13
Why is it necessary to find such quote replacements (```%: :%```) if I could just use the right quotes in augmented user defined fields whenever I need to?

The default projection (= fields defined in RowStructure) could at least always be escaped by default. That wouldn't break the above insert statement. For augmented projections, quoting could be left in the responsibility of the user.

**Comment by chanmix51** [comment] 2015-02-25 21:19
The problem with quoting comes from the ability of the projection to prepend a table alias of a field in a complex definition:

```php
$projection->setField('is_odd', '%:something:% % 2 <> 0', 'bool');
// returning …, my_table."something" % 2 <> 0 as "is_odd", …
```

So we need to be able to spot fields in the way they are defined in the database and quote them.

**Comment by chanmix51** [comment] 2015-03-03 08:25
The branch `projection` will be merged into master **friday 6th of March 2015**.

**Comment by chanmix51** [comment] 2015-03-06 13:45
Done

**Closed by chanmix51** 2015-03-06 13:45 UTC
