### ISSUE TITLE
ResultIterator::isLast should return true on empty Model/CollectionIterator

### ISSUE THREAD

**Issue by ishenkoyv** [pomm-project/Foundation#60] opened 2015-07-31 13:14 UTC
I think if collection doesn't contain any elements ResultIterator should return true on isLast method call. Currently

```
$this->collection->count() -> 0
$this->collection->isLast() -> false
```

What do you think?

**Comment by chanmix51** [comment] 2015-08-02 20:25
I am not sure I do agree with that. `isFirst()` and `isLast()` methods do provide informations for the current record of a collection. If no records are returned, `isLast()` could not either be true nor false imho since a non existent record cannot be the last and cannot be not the last. I'd say these methods should then return NULL (unknown). 

Any more thoughts ?

**Comment by ishenkoyv** [comment] 2015-08-02 21:14
I agree. NULL is more appropriate method result for empty collection and php handle it as false on logic operations.
Would you like I make pull request?

**Comment by chanmix51** [comment] 2015-08-03 08:18
We have to be careful not to introduce regressions on existing applications.

**Comment by chanmix51** [comment] 2015-08-14 19:33
The fix has been committed in a separate branch to let people test and adapt their code before it gets into master.

**Closed** 2015-08-31 10:32 UTC
Labels: Request For Comments
